export default {
    about_us:'Acerca de nosotros',
    contact_details:'Detalles de contacto',
    email:'Email :',
    phone:'Teléfono :',
    driver_account_approve_err:'Su cuenta no está aprobada todavía como conductor.',
    account_not_exsist:'Su cuenta no existe como conductor.',
    driver_ride_complete_status:' El conductor ha completado su viaje. Su identificación de reserva es',
    please_wait:'Calculando su tarifa',
    on_trip:'En viaje',
    complete_trip:'VIAJE COMPLETO',
    account_successful_done:'Su cuenta se ha creado correctamente y está esperando la aprobación del administrador.',
    image_size_error:'El tamaño de la imagen no debe ser mayor a 2mb.',
    password_blank_error:'La contraseña no puede estar en blanco.',
    password_complexity_alphabet:'La contraseña debe tener al menos 1 carácter alfanumérico y 8-15 de longitud.',
    password_complexity_complex:'La contraseña debe tener al menos 1 letra mayúscula, 1 letra minúscula, 1 número y 1 carácter especial con 6-10 de longitud.',
    driver_registration:'Registro de conductor',
    first_name:'Nombre',
    first_name_error:'Por favor, introduzca su nombre',
    last_name:'Apellido',
    last_name_error:'Por favor ingrese su apellido',
    email:'Email',
    email_blank_error:'Por favor, introduzca una dirección de correo electrónico válida',
    mobile:'Número de teléfono móvil',
    mobile_no_blank_error:'Por favor, introduzca el número de teléfono móvil',
    password:'Contraseña',
    confrim_password:'Confirmar contraseña',
    password_not_match:'Las contraseñas no coinciden',
    vehicle_model_name:'Modelo del vehículo',
    vehicle_model_name_blank_error:'El modelo del vehículo no puede estar en blanco',
    vehicle_reg_no:'Matrícula del vehículo',
    vehicle_number_blank_err:'La matrícula del vehículo no puede estar en blanco',
    upload_driving_lisence:'Imágen de licencia de conducir',
    image_size_warning:'(Tamaño de imagen: Max 2 MB)',
    reg_no:'Regístrate ahora',
    update_profile:'Actualización del perfil',
    valid_mobile_number:'Por favor, introduzca un número de celular válido',
    update_now:'Actualizar ahora',
    no_notification:'No se encontró ninguna notificación.',
    forgot_password:'Se te olvidó tu contraseña?',
    valid_email_err:'Por favor, introduce una dirección de correo electrónico válida',
    send_email:'Enviar correo electrónico',
    enter_code:'Ingresar código',
    submit:'Enviar',
    change_password:'Cambiar contraseña?',
    old_password:'Contraseña anterior',
    old_password_err:'Por favor ingrese su contraseña anterior',
    new_password:'Nueva contraseña',
    new_password_err:'Por favor ingrese su nueva contraseña',
    update:'Actualizar',
    login:'Iniciar sesión',
    booking_request:'Solicitudes de reserva',
    profile_settings:'Configuración de perfil',
    incomeText:"Mis ganancias",
    my_bookings:'Mis reservas',
    about_us:'Acerca de nosotros',
    sign_out:'Cerrar sesión',
    rider_ride_cancel_text:'El conductor ha cancelado el viaje.',
    mobile_no_found:'Número de celular no encontrado',
    otp_error:'Por favor ingrese la OTP correcta',
    driver_journey_err:'El conductor comenzó su viaje. Su identificación de reserva es',
    on_trip:'En viaje',
    wait_for_rider:'ESPERE AL USUARIO',
    rider_notified:'El chofer ha sido notificado',
    start_trip:'INICIAR VIAJE',
    cancel_reson_1:'No se puede contactar al conductor',
    cancel_reson_2:'El vehículo no viene en mi dirección.',
    cancel_reson_3:'Mi razón no está en la lista.',
    cancel_reson_4:'No se observa al conductor',
    cancel_reson_5:'El vehículo no llega a la hora prevista',
    api_error:'Google coloca error de API',
    accept_booking_request:'Acepta tu solicitud de reserva',
    pickup_location:'Lugar de recojo',
    drop_location:'Lugar de destino',
    ignore_text:'Ignorar',
    modal_close:'Modal ha sido cerrado.',
    alert_text:'Alerta',
    ignore_job_title:'¿Quieres ignorar este trabajo?',
    cancel:'Cancelar',
    ok:'OK',
    accept:'Aceptar',
    task_list:'Lista de tareas',
    rider_not_here:'Actualmente no hay conductores en su área',
    booking_request_rejected:'Su solicitud de reserva ha sido rechazada por el conductor solicitado',
    driver_requested_for_payment:'El conductor ha solicitado el pago. Su identificación de reserva es',
    request_payment:'SOLICITAR PAGO',
    my_rides:'Mis viajes',
    password_reset_link:'Un enlace para restablecer su contraseña ha sido enviado a su correo, compruebe y restablezca su nueva contraseña.',
    notification:'Notificaciones',
    chat_blank:'Por favor escribe algo...',
    send_msg:', te envió un mensaje: \n',
    driver:'Conductor',
    chat_history_not_found:'No se encontró el historial de chat',
    chat:'Chat',
    send:'Enviar',
    type_messege:'Escribe tu mensaje',
    photo_upload_action_sheet_title:'Elija un tipo de medio ?',
    camera:'Cámara',
    galery:'Galería',
    cancel:'Galería',
    yes:'si',
    password_change:'Tu contraseña se actualizó correctamente',
    password_not_match:'Las contraseñas no coinciden',
    confrim:'Confirmación',
    delete_account:'¿ Quieres eliminar tu cuenta ?',
    my_profile:'Mi perfil',
    active_status:'Estado activo',
    profile_details:'Detalles del perfil',
    location:'Ubicación',
    mobile_no:'Número de teléfono móvil',
    preffered_lang:'Idioma preferido',
    lang:'Español',
    delete_account:'Borrar cuenta',
    payment_info:'Información de pago del conductor',
    booking_details:'Detalles de mis reservas',
    you_rate_text:'Has sido calificado',
    no_rated_text:'No tienes calificación',
    bill_details:'Detalles de pago',
    your_trip:'Detalles de factura',
    total_bill:'Cuenta total',
    include_tax:'Incluye todos los impuestos',
    total_payable:'Mi comisión',
    go_to_booking:'Ir a reserva',
    my_booking:'Mis reservas',
    job_ignore:'¿Quieres ignorar este trabajo?',
    show_modal:'Mostrar modal',
    notification_title:'Notificación Segutaxi',
    register:'Registrarse',
    today:'Ganancias de hoy',
    thismonth:'Ganancias del mes',
    totalearning:'Ganancias totales',
    convenienceFee:'Costos extras',
    paymentStatus:'Estado de pago',
    payment_mode:'Modo de pago',
    customer_payable:'Conductor a pagar',
    discount_amount:'Importe de descuento',
    CardPaymentAmount:'Pagar con tarjeta -',
    CashPaymentAmount:'Pagar en efectivo -',
    WalletPayment:'Pagar con billetera -',
    android_channel: 'Notificaciones de Segutaxi'
}